DROP DATABASE IF EXISTS VideoGameDB;
CREATE DATABASE VideoGameDB;
USE VideoGameDB;
ALTER DATABASE VideoGameDB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `vg_table`(
    `game_id` INT(11) NOT NULL AUTO_INCREMENT,
    `game_name` VARCHAR(255) NOT NULL,
    `genre` VARCHAR(255) NOT NULL,
    `publisher` VARCHAR(150) NOT NULL,
    `platforms` VARCHAR(500) NOT NULL,
    `pegi_age` VARCHAR(20) NOT NULL,
    `release_date` DATE NOT NULL,
    `description` VARCHAR(4000),
    PRIMARY KEY (`game_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='datatable videogames';

INSERT INTO vg_table VALUES(1, "Speedy Blupi", "Arcade", "eGames", "PC", "3", "1998-09-13", "Speedy Blupi is a parallax side-scrolling action game where the title character and hero has a phenomenal vertical leap. Blupi must travel through a rich variety of levels using his ability to walk left or right, look up or down, and also jump extremely high. While he has no direct offensive capabilities, there are a number of power-ups that help him along his way. These include jet packs and skateboards. Blupi faces a variety of threats to his well-being, most notably bombs, lava, and some roving, exploding tractors. Each level has treasure that Blupi can collect along with actual eggs which double as one-ups.");
INSERT INTO vg_table VALUES(2, "Speedy Blupi 2", "Arcade", "eGames", "PC", "3", "2001-09-13", "Speedy Blupi is back and he's better than ever in this all-new, action-packed side-scrolling adventure game. As Blupi, your goal is to collect as many eggs and treasure chests as possible before the game ends. There's an astounding 60 missions where you will work your way through puzzling obstacles, swim with dangerous sharks, fly your way to safety from dizzying heights, and so much more! You never know what's going to happen next when it comes to the fearless Blupi - this is an all-new adventure that you won't want to miss!");
INSERT INTO vg_table VALUES(3, "Path of Exile", "Action, RPG, MMO, Indie", "Grinding Gear Games", "PC, PlayStation 4, PC", "18", "2013-10-23", "Players wake up on grim shores of Wraeclast. Without any knowledge who we are or what have we done, players must start to explore an aggressive and cruel fantasy world of criminals, bandits and murderers. Discover the mystery of a long forgotten the Eternal Empire, and survive.");
INSERT INTO vg_table VALUES(4, "Sonic the Hedgehog", "Platformer", "SEGA", "Xbox 360, PlayStation 3", "12", "2006-11-14", "Get set for some real adventure with the Sonic the Hedgehog platform video game. Opening with the abduction scene of the beautiful princess Soleanna by Dr. Eggman, this Xbox 360 video game takes you through a wide range of obstacles in order to deter EggMan of his evil plan to destroy the land. Sonic the Hedgehog lets you explore the town’s surroundings, interact with characters, and play mini games when in town. Outside the town, this Xbox 360 video game brings the character’s trademark speed and moves to the fore. Furthermore, the advanced features of the Xbox 360 consoles help this platform video game build upon a dynamic environment.");
INSERT INTO vg_table VALUES(5, "Sonic the Hedgehog", "Action, Adventure, Arcade", "SEGA", "Nintendo 3DS, Wii, Xbox 360, PlayStation 3, iOS, PC, Genesis, Game Gear, Android, Game Boy Advance", "3", "1991-06-23", "The game takes place on South Island and follows Sonic — an anthropomorphic blue hedgehog. The game’s antagonist, a brilliant but insane scientist Dr. Robotnik attempts to take possession of the power of six Chaos Emeralds by entrapping South Island’s animal inhabitants inside hostile robots. Sonic decides to hinder Robotnik’s plans by freeing animals and collecting the emeralds himself.");
INSERT INTO vg_table VALUES(6, "Super Paper Mario", "RPG, Platformer", "Nintendo", "Wii, Wii U", "3", "2007-04-09", "Mario flips out on an adventure through eight exciting and vibrant worlds! Switch from 2D to 3D to avoid enemies, find secret passages, grab hidden items, and shake the Wii Remote for stylish moves! Uncover hilarious plot-twists as you power-up with new friends and even play as Peach and Bowser!");
INSERT INTO vg_table VALUES(7, "Final Fantasy", "RPG", "Nintendo, Square Enix", "Wii, Wii U, iOS, Nintendo 3DS, PlayStation, NES", "7", "1987-12-17", "The first Final Fantasy story follows four youths called the Light Warriors, who each carry one of their world's four elemental crystals which have been darkened by the four Elemental Fiends. Together, they quest to defeat these evil forces, restore light to the crystals, and save their world.");
INSERT INTO vg_table VALUES(8, "Dr. Robotnik's Mean Bean Machine", "Puzzle", "SEGA", "SEGA Master System, Nintendo 3DS, Genesis, PC, Wii, Game Gear, GameCube", "3", "1993-11-26", "Dr. Robotnik's Mean Bean Machine is the Westernized version of Puyo Puyo and replaces its characters with those from the Sonic the Hedgehog franchise, being primarily based on the Adventures of Sonic the Hedgehog animated series. The gameplay is reminiscent of Tetris, in which the player must organise different coloured shapes as they fall down a board.");
INSERT INTO vg_table VALUES(9, "Diablo 3: Ultimate Evil Edition", "Action, RPG", "Blizzard Entertainment", "PlayStation 3, Xbox One, PC, Xbox 360, PlayStation 4", "16", "2014-08-19", "Diablo III: Ultimate Evil Edition is a Diablo game for consoles. It effectively combines Diablo III and Reaper of Souls into a single game, including its five acts, the Crusader class, and bounties.");
INSERT INTO vg_table VALUES(10, "Minecraft", "Action, Simulation, Arcade, MMO, Indie", "Microsoft Studios", "Android, PlayStation 4, PlayStation 3, Nintendo 3DS, Nintendo Switch, Linux, macOS, PC, iOS, Xbox One, Wii U, Xbox 360, PS Vita", "7", "2011-11-18", "One of the most popular games of the 2010s, Minecraft allows you to rebuild the environment around you. The world of the game is open, infinitely wide, and procedurally generated. It is composed of small 3D cubes that represent specific types of materials or terrain. The gameplay is centered on mining and building various structures of your choice. You can also craft items like tools, weapons, and armor.");
INSERT INTO vg_table VALUES(11, "Pokémon Diamond", "Adventure, RPG", "Nintendo, The Pokemon Company", "Nintendo DS", "3", "2007-04-22", "Pokémon Diamond and Pearl are part of the Generation IV Pokémon game series. These games take place in the Sinnoh region, and are the first main series Pokémon game for the Nintendo DS.");
INSERT INTO vg_table VALUES(12, "Pokémon Pearl", "Adventure, RPG", "Nintendo, The Pokemon Company", "Nintendo DS", "3", "2007-04-22", "Pokémon Diamond and Pearl are part of the Generation IV Pokémon game series. These games take place in the Sinnoh region, and are the first main series Pokémon game for the Nintendo DS.");
INSERT INTO vg_table VALUES(13, "Carrion", "Action, Adventure, Indie", "Devolver Digital", "Nintendo Switch, Linux, macOS, PC, Xbox One, PlayStation 4", "16", "2020-07-23", "Carrion is a reverse horror game in which you assume the role of an amorphous alien being. Use your unique otherworldly abilities to your advantage and hunt down your prey!");
INSERT INTO vg_table VALUES(14, "Screamer", "Action, Simulation, Sports, Racing", "Interplay Productions", "PC, macOS", "3", "1995-10-30", "Lights blur. The crowd whizzes past. Your helmet rattles against the roll bar and the competition switches into overdrive. Tears stream from your eyes and the race moves into extreme speed. Tears of sweat. The same stuff that's seeping off your palms and onto the steering wheel. Get a grip. You're sliding into a turn at 200 miles per hour and centrifugal force will only carry you so far. This is velocity-driven, pedal-to-the-metal arcade racing. Strapped into a personally chosen made-for-the-Autobahn racing machine, you'll scream to redefine fast in this winding 3D ride of pure fun.");
INSERT INTO vg_table VALUES(15, "Super Mario Galaxy", "Platformer", "Nintendo", "Wii, Nintendo Switch, Wii U", "3", "2007-11-12", "Become Mario as he traverses gravity-bending galaxies, traveling in and out of gravitational fields by blasting from planet to planet. Control Mario with the Wii Remote™ and Nunchuk™. Power-up to reach inaccessible areas. Collect Star Bits to either stun enemies or feed Lumas.");
INSERT INTO vg_table VALUES(16, "South Park: The Stick of Truth", "Adventure, RPG", "Ubisoft Entertainment", "Xbox 360, Nintendo Switch, PC, Xbox One, PlayStation 4, PlayStation 3", "18", "2014-03-04", "South Park: The Stick of Truth is an action RPG based on the American animated series South Park. Players assume the role of the New Kid, who moved to eponymous fictional town in Colorado State with his parents. According to the storyline, the New Kid meets the army of humans led by Wizard King Cartman in the Kupa Keep Kingdom (Cartman’s backyard) and gets his nickname Douchebag. Cartman, as well as other characters of the original series, introduce The Stick of Truth, the key to the war between humans and elves, to the New Kid. Once The Stick is stolen by elves, the war and the whole adventure of Douchebag begins. The game is viewed from the third-person perspective. To start the campaign, players have to choose one of the character types (Fighter, Thief, Mage, and Jew), each with its own parameters and special abilities. Completing the levels and eliminating the enemies gives experience points that could be spent on learning new skills or upgrading the level. The gameplay also features fast travel ability. Remarkable characters of the original series – Cartman, Butters, Stan, and Kyle – join the protagonist during his wild adventure.");
INSERT INTO vg_table VALUES(17, "South Park: The Fractured But Whole", "Adventure, RPG", "Ubisoft Entertainment", "Nintendo Switch, PC, Xbox One, PlayStation 4", "18", "2017-03-31", "Gameplay-wise the game has not changed much: it's still a game similar to jRPG with step-by-step battles and a pseudo-open world, which is divided into story locations. Using a 2.5D player explores the fictional town of South Park Colorado. In the game, classes are available, and they are South Park-style satire on the classic RPG classes. The main change in the combat system is visual: now instead of a static battlefield, players and NPCs can move freely along the battlefield divided into blocks and use its features to create a tactical advantage.");
INSERT INTO vg_table VALUES(18, "Undertale", "RPG, Indie", "8-4, Toby Fox", "Xbox Series S, Xbox Series X, PS Vita, PlayStation 4, Linux, macOS, PC, Xbox One, Nintendo Switch", "12", "2015-09-14", "Undertale uses pixelated graphics and traditional mechanics of RPGs such as earning experience points, having an open world, and so on. As the game goes on, the player has to solve several puzzles and interact with NPCs. The battles in the game are represented using the bullet hell mini-games with the player having an option to choose where they want to spare their opponent or hit the enemy back. Monsters behavior depends on the player's actions: if one decides to use a peaceful approach it will be easier to dodge the enemies attacks and vice versa.");
INSERT INTO vg_table VALUES(19, "Autobahn Total", "Racing, Arcade", "IncaGold", "PC", "Not Rated", "2004-01-01", "32 different challenge/tracks and 10 different levels of difficulty lay down hours of ripe road. Do time trials or go for the one-on-one duel against Germany's quickest and most daring drivers (still) alive. Navigate sunny, cloudy and rainy conditions to save yourself. Race any time of day or night - the Autobahn doesn't close. Tracks up to 16 miles long lie waiting for your ride.");
INSERT INTO vg_table VALUES(20, "Valheim", "Action, Adventure, Indie", "Coffee Stain", "Linux, PC", "Not Rated", "2021-02-02", "Prove your worth! Are you worthy of entering Valhalla? You have been sent to Valheim, the 10th Norse world. Only by defeating the mighty beasts of these lands will you win the favor of the gods. This quest will take you to the far reaches of this world, from the deepest forest to the highest mountain peak. You will craft powerful weapons, build unyielding castles and sail longships towards the horizon.");
INSERT INTO vg_table VALUES(21, "Forza Horizon 5", "Action, Adventure, Simulation, Sports, Racing", "Playground Games", "PC, Xbox Series S, Xbox Series X, Xbox One", "3", "2021-11-08", "Your Ultimate Horizon Adventure awaits! Explore the vibrant and ever-evolving open world landscapes of Mexico with limitless, fun driving action in hundreds of the world’s greatest cars. Explore a world of striking contrast and beauty. Discover living deserts, lush jungles, historic cities, hidden ruins, pristine beaches, vast canyons and a towering snow-capped volcano.");
INSERT INTO vg_table VALUES(22, "Peggle", "Arcade, Puzzle", "PopCap Games", "PC, Xbox 360, PlayStation 3", "3", "2007-02-27", "Do you have what it takes to become a Peggle™ Master? Take your best shot! Conquer 55 levels with 10 mystical Magic Powers and rack up bonus points. Face off against friends in 4-player Xbox LIVE® multiplayer play, and test your skills in 75 Grand Master Challenges.");
INSERT INTO vg_table VALUES(23, "", "", "", "", "", "", "");
INSERT INTO vg_table VALUES(24, "", "", "", "", "", "", "");
INSERT INTO vg_table VALUES(25, "", "", "", "", "", "", "");
INSERT INTO vg_table VALUES(26, "", "", "", "", "", "", "");
INSERT INTO vg_table VALUES(27, "", "", "", "", "", "", "");
INSERT INTO vg_table VALUES(28, "", "", "", "", "", "", "");
INSERT INTO vg_table VALUES(29, "", "", "", "", "", "", "");
INSERT INTO vg_table VALUES(30, "", "", "", "", "", "", "");